In [12]:
import h5py
import numpy as np


In [20]:
with h5py.File(r'news_inputs/text_data_input.h5', 'r') as f:
  for set in f:
    print(np.shape(f[set]))

(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111451)
(2868, 111

In [18]:
with h5py.File(r'stock_inputs/stock_inputs.h5', 'r') as f:
  for set in f:
    print(f[set][:])

[[-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 [-1 -1 -1 ... -1 -1 -1]
 ...
 [ 1  1  1 ...  1 -1  1]
 [-1  1  1 ...  1  1  1]
 [ 1 -1 -1 ... -1 -1  1]]
